-- Supabase SQL Editor'e yapıştırıp çalıştır.
create table if not exists public.coins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  country text not null,
  year integer not null,
  value text not null,
  unit text not null,
  created_at timestamptz not null default now()
);

alter table public.coins enable row level security;

drop policy if exists "Users can view their own coins" on public.coins;
create policy "Users can view their own coins"
on public.coins for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own coins" on public.coins;
create policy "Users can insert their own coins"
on public.coins for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own coins" on public.coins;
create policy "Users can update their own coins"
on public.coins for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own coins" on public.coins;
create policy "Users can delete their own coins"
on public.coins for delete
to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.coins to authenticated;
grant usage, select on sequence public.coins_id_seq to authenticated;
